import json, sys
sys.stdout.reconfigure(encoding='utf-8')

with open('notebooks/phase1_baseline.ipynb', encoding='utf-8') as f:
    nb = json.load(f)

new_cell1 = (
    "# ── Cell 1: Install / pin dependencies ───────────────────────────────────────\n"
    "# ROOT CAUSE of v14/v15 NCCL failure (documented for traceability):\n"
    "#   v14/v15 installed torch==2.2.2+cu118 FIRST, then pip-installed transformers\n"
    "#   and bitsandbytes. Those packages re-upgraded torch to the Kaggle system\n"
    "#   version (~2.10+cu128), which requires ncclCommShrink@NCCL_2.21. The stub\n"
    "#   was built from 2.2.2's libtorch_cuda.so (no ncclCommShrink), so when Python\n"
    "#   imported the upgraded torch the stub could not satisfy the new symbol.\n"
    "#\n"
    "# v16-v20 FIX HISTORY:\n"
    "#   v16: install non-torch deps first, pin torch last — fixes torch re-upgrade\n"
    "#   v17: drop --no-deps — fixes missing libcudart.so.11.0\n"
    "#   v18: numpy<2 + bitsandbytes==0.43.3 — bitsandbytes 0.49+ needs torch>=2.3\n"
    "#   v19: numpy==1.26.4 --force-reinstall — wrong: pip can't replace Kaggle's\n"
    "#        baked-in .so files; numpy 1.x .py + 2.x .so = ABI mismatch crash\n"
    "#   v20: uninstall jax/jaxlib/flax — removes the is_flax_available() numpy.random\n"
    "#        crash chain; Kaggle numpy .so files are system-locked, can't downgrade\n"
    "#   v21: pin triton==2.2.0 — kaggle has triton 3.x; triton.ops removed in 3.0;\n"
    "#        bitsandbytes 0.43.3 imports triton.ops.matmul_perf_model unconditionally\n"
    "#        FAILED: triton 2.2.0 has no cp312 wheel; pip -q silently skipped it\n"
    "#   v22: triton==2.3.0 — first 2.x release with cp312 wheel; has triton.ops\n"
    "#   v23: --no-deps on vlam install — pyproject.toml torch>=2.2.0 dep was\n"
    "#        upgrading torch 2.2.2 → 2.3.1 (then triton 3.x came back)\n"
    "#   v24: pin torchvision==0.17.2+cu118 — system 0.25.0 calls\n"
    "#        torch.library.register_fake which doesn't exist in torch 2.2.x\n"
    "#\n"
    "# GPU COMPATIBILITY:\n"
    "#   P100 = sm_60; torch 2.4+ dropped sm_60 support. Pin torch==2.2.2+cu118.\n"
    "#\n"
    "# NCCL COMPATIBILITY (torch 2.2.2+cu118 on Kaggle P100):\n"
    "#   libtorch_cuda.so references nccl* symbols; no matching libnccl.so exists.\n"
    "#   We compile a zero-stub exporting all nccl* symbols and load RTLD_GLOBAL.\n"
    "#\n"
    "# OpenVLA version pins:\n"
    "#   transformers==4.40.1  — only version tested by OpenVLA authors\n"
    "#   tokenizers==0.19.1    — must match transformers 4.40.1\n"
    "#   timm==0.9.10          — imported by modeling_prismatic.py\n"
    "#   sentencepiece==0.1.99 — LLaMA-2 tokenizer\n"
    "import subprocess, sys, os, ctypes, re, glob as _glob\n"
    "\n"
    "def _pip(*args, check=True):\n"
    "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', *args], check=check)\n"
    "\n"
    "# ── 1. Detect GPU SM version BEFORE any torch import ─────────────────────────\n"
    "_sm_ver = 70\n"
    "try:\n"
    "    _smi = subprocess.run(\n"
    "        ['nvidia-smi', '--query-gpu=compute_cap', '--format=csv,noheader'],\n"
    "        capture_output=True, text=True, timeout=15,\n"
    "    )\n"
    "    if _smi.returncode == 0:\n"
    "        _cap = _smi.stdout.strip().split('\\n')[0].strip()\n"
    "        _sm_ver = int(_cap.replace('.', ''))\n"
    "        print(f'nvidia-smi: compute_cap={_cap}  (sm_{_sm_ver})')\n"
    "except Exception as _e:\n"
    "    print(f'nvidia-smi check skipped ({_e}) — assuming sm_70+')\n"
    "\n"
    "# ── 2. Install ALL non-torch deps FIRST ──────────────────────────────────────\n"
    "# These may pull in a newer torch as a transitive dep; we override in step 3.\n"
    "print('Installing non-torch deps ...')\n"
    "_pip(\n"
    "    'transformers==4.40.1',\n"
    "    'tokenizers==0.19.1',\n"
    "    'timm==0.9.10',\n"
    "    'sentencepiece==0.1.99',\n"
    ")\n"
    "_pip(\n"
    "    'triton==2.3.0',         # kaggle has triton 3.x; triton.ops removed in 3.0; bnb 0.43.3 needs 2.x\n"
    "                             # triton 2.2.0 has no cp312 wheel; 2.3.0 is the earliest with cp312\n"
    "    'accelerate>=0.27.0',\n"
    "    'bitsandbytes==0.43.3',  # 0.49+ requires torch>=2.3 and uses is_compiling/has_xpu\n"
    "    'pynvml',\n"
    "    'av',\n"
    "    'datasets',\n"
    "    'PyYAML',\n"
    "    'tqdm',\n"
    ")\n"
    "print('Non-torch deps installed.')\n"
    "\n"
    "# ── 3. Pin SM-compatible torch LAST so it wins over any transitive upgrade ───\n"
    "# Install WITH deps so that nvidia-cuda-runtime-cu11 (provides libcudart.so.11.0)\n"
    "# and other CUDA runtime packages are installed. --no-deps caused v16 to fail\n"
    "# because libcudart.so.11.0 was missing at torch import time.\n"
    "if _sm_ver < 70:\n"
    "    print(f'sm_{_sm_ver} < 70 → pinning torch==2.2.2+cu118 + torchvision==0.17.2+cu118 ...')\n"
    "    _pip(\n"
    "        'torch==2.2.2+cu118',\n"
    "        'torchvision==0.17.2+cu118',  # system has 0.25.0+cu128 which calls torch.library.register_fake (torch 2.4+)\n"
    "        '--index-url', 'https://download.pytorch.org/whl/cu118',\n"
    "    )\n"
    "    print('torch==2.2.2+cu118 + torchvision==0.17.2+cu118 pinned.')\n"
    "else:\n"
    "    print('sm_70+ → using default Kaggle torch.')\n"
    "\n"
    "# ── 4. Uninstall JAX/Flax ────────────────────────────────────────────────────\n"
    "# Kaggle pre-installs JAX/Flax. transformers.is_flax_available() detects them\n"
    "# and eagerly imports jax, whose k8s_cluster module calls np.random.rand at\n"
    "# module load time. On Kaggle, numpy .so files are baked into the system\n"
    "# Python and cannot be replaced by pip; any numpy downgrade produces a\n"
    "# Python-level / .so ABI mismatch (dtype size 96 vs 88) causing a crash.\n"
    "# Removing JAX/Flax stops that import chain. We do not use them.\n"
    "print('Uninstalling jax/jaxlib/flax (not needed; avoids numpy.random ABI mismatch) ...')\n"
    "subprocess.run(\n"
    "    [sys.executable, '-m', 'pip', 'uninstall', '-y', 'jax', 'jaxlib', 'flax'],\n"
    "    check=False,\n"
    ")\n"
    "_np_diag = subprocess.run(\n"
    "    [sys.executable, '-c',\n"
    "     'import numpy; print(\"numpy\", numpy.__version__, numpy.__file__)'],\n"
    "    capture_output=True, text=True, timeout=30,\n"
    ")\n"
    "print(_np_diag.stdout.strip() or _np_diag.stderr.strip())\n"
    "\n"
    "# ── 5. NCCL stub (sm_60 only) ─────────────────────────────────────────────────\n"
    "# torch==2.2.2+cu118 links against nccl* symbols with no matching libnccl.so\n"
    "# on the Kaggle P100 runtime. Compile a zero-stub exporting all undefined\n"
    "# nccl* symbols found in libtorch_cuda.so and load RTLD_GLOBAL before torch.\n"
    "#\n"
    "# Built AFTER all pip installs so objdump scans the FINAL libtorch_cuda.so.\n"
    "if _sm_ver < 70:\n"
    "\n"
    "    def _find_libtorch_cuda():\n"
    "        for _pat in [\n"
    "            '/usr/local/lib/python*/dist-packages/torch/lib/libtorch_cuda.so',\n"
    "            '/opt/conda/lib/python*/site-packages/torch/lib/libtorch_cuda.so',\n"
    "        ]:\n"
    "            _hits = _glob.glob(_pat)\n"
    "            if _hits:\n"
    "                return _hits[0]\n"
    "        raise FileNotFoundError('libtorch_cuda.so not found — torch install failed')\n"
    "\n"
    "    def _nccl_undef_syms(path):\n"
    "        \"\"\"Return {sym_name: version_str|None} for nccl* UNDEF symbols.\"\"\"\n"
    "        r = subprocess.run(['objdump', '-T', path],\n"
    "                           capture_output=True, text=True, timeout=60)\n"
    "        syms = {}\n"
    "        for line in r.stdout.splitlines():\n"
    "            if '*UND*' not in line:\n"
    "                continue\n"
    "            # Parenthesised version: (NCCL_2.21)  ncclCommShrink\n"
    "            # Use [\\w.]+ (not \\w+) — version strings contain dots.\n"
    "            m = re.search(r'\\(([\\w.]+)\\)\\s+(nccl\\w+)', line)\n"
    "            if m:\n"
    "                syms[m.group(2)] = m.group(1)\n"
    "                continue\n"
    "            # Space-separated version: NCCL_2.21   ncclCommShrink\n"
    "            m2 = re.search(r'\\*UND\\*\\s+\\S+\\s+(NCCL_[\\d.]+)\\s+(nccl\\w+)', line)\n"
    "            if m2:\n"
    "                syms[m2.group(2)] = m2.group(1)\n"
    "                continue\n"
    "            # Unversioned\n"
    "            m3 = re.search(r'\\s+(nccl\\w+)\\s*$', line)\n"
    "            if m3:\n"
    "                syms.setdefault(m3.group(1), None)\n"
    "        if not syms:\n"
    "            # nm -D fallback\n"
    "            r2 = subprocess.run(['nm', '-D', path],\n"
    "                                capture_output=True, text=True, timeout=60)\n"
    "            for line in r2.stdout.splitlines():\n"
    "                parts = line.split()\n"
    "                if len(parts) >= 2 and parts[-2] == 'U' and parts[-1].startswith('nccl'):\n"
    "                    syms[parts[-1]] = None\n"
    "        return syms\n"
    "\n"
    "    _libtorch_cuda = _find_libtorch_cuda()\n"
    "    print(f'Scanning NCCL symbols in: {_libtorch_cuda}')\n"
    "    _nccl_syms = _nccl_undef_syms(_libtorch_cuda)\n"
    "    print(f'Found {len(_nccl_syms)} undefined nccl* symbols:')\n"
    "    for _sym, _ver in sorted(_nccl_syms.items()):\n"
    "        print(f'  {_sym}  @{_ver or \"(unversioned)\"}')\n"
    "\n"
    "    # Build C stub\n"
    "    _c_lines = ['#include <stddef.h>', '']\n"
    "    for _sym, _ver in sorted(_nccl_syms.items()):\n"
    "        _internal = f'_stub_{_sym}'\n"
    "        _c_lines.append(f'int {_internal}(void) {{ return 0; }}')\n"
    "        if _ver:\n"
    "            # .symver @@ = default version; satisfies @<ver> references\n"
    "            _c_lines.append(f'__asm__(\".symver {_internal},{_sym}@@{_ver}\");')\n"
    "        else:\n"
    "            _c_lines.append(\n"
    "                f'extern int {_sym}(void) __attribute__((alias(\"{_internal}\")));'\n"
    "            )\n"
    "        _c_lines.append('')\n"
    "\n"
    "    _stub_c  = '/tmp/_nccl_stub.c'\n"
    "    _stub_so = '/tmp/_nccl_stub.so'\n"
    "    with open(_stub_c, 'w') as _f:\n"
    "        _f.write('\\n'.join(_c_lines))\n"
    "\n"
    "    _gcc = subprocess.run(\n"
    "        ['gcc', '-shared', '-fPIC', '-nostartfiles', '-o', _stub_so, _stub_c],\n"
    "        capture_output=True, text=True, timeout=30,\n"
    "    )\n"
    "    if _gcc.returncode != 0:\n"
    "        print(f'GCC stderr:\\n{_gcc.stderr.strip()}')\n"
    "        raise RuntimeError('NCCL stub compilation failed')\n"
    "\n"
    "    ctypes.CDLL(_stub_so, mode=ctypes.RTLD_GLOBAL)\n"
    "    print(f'NCCL stub loaded (RTLD_GLOBAL): {_stub_so}')\n"
    "\n"
    "    # Smoke-test: import torch now to catch NCCL issues before 15 GB download\n"
    "    import torch as _torch_smoke\n"
    "    print(f'torch {_torch_smoke.__version__} imported OK ✓')\n"
    "    _cuda_ok = _torch_smoke.cuda.is_available()\n"
    "    _dev = _torch_smoke.cuda.get_device_name(0) if _cuda_ok else 'N/A'\n"
    "    print(f'CUDA: available={_cuda_ok}, device={_dev}')\n"
    "    del _torch_smoke\n"
    "\n"
    "print('Cell 1 complete.')\n"
)

nb['cells'][1]['source'] = [new_cell1]
nb['cells'][1]['outputs'] = []
nb['cells'][1]['execution_count'] = None

with open('notebooks/phase1_baseline.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print('Notebook updated successfully.')
