bitsandbytes_version: 0.43.3
cuda_version: '11.8'
driver_version: 580.159.04
gpu_multi_proc: 56
gpu_name: Tesla P100-PCIE-16GB
gpu_vram_gb: 15.89
model_precision: FP16
n_params_b: 7.541
n_params_total: 7541237184
peak_mem_load_mib: 13791.7
platform: Linux-6.12.90+-x86_64-with-glibc2.35
sm_version: sm_60
torch_version: 2.2.2+cu118
transformers_version: 4.40.1
